name: Tests
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua_version: [5.1, 5.2, 5.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Lua/LuaJIT
        uses: leafo/gh-actions-lua@v10.0.0
        with:
          luaVersion: ${{ matrix.lua_version }}
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install modules
        run: |
          luarocks install luacov
          luarocks install luacov-reporter-lcov
          luarocks install busted
      - name: Lua Busted
        run: |
          busted --version
          busted --verbose --output=gtest
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: ./luacov.report.out
          #minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
